// apps/vue/src/components/FeatureForm.vue
<template>
    <form class="ft-form" novalidate v-on:submit.prevent="submit()">

        <label class="mdc-text-field" v-mdc-text-field="{value: form.key, valid: !errors.key, required: true}">
            <span class="mdc-text-field__ripple"></span>
            <input aria-controls="key-helper-text-id" aria-describedby="key-helper-text-id" aria-labelledby="key-id"
                   autofocus
                   class="mdc-text-field__input" type="text" v-model="form.key">
            <span class="mdc-floating-label" id="key-id">Key</span>
            <span class="mdc-line-ripple"></span>
        </label>
        <div aria-hidden="true" class="mdc-text-field-helper-line" id="key-helper-text-id">
            <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" v-if="errors.key"
                 v-mdc-text-field-helper-text>
                {{errors.key}}
            </div>
            <div class="mdc-text-field-helper-text" v-else v-mdc-text-field-helper-text>This will be used as key in the
                response object
            </div>
        </div>

        <label class="mdc-text-field" v-mdc-text-field="{value: form.description, valid: !errors.description}">
            <span class="mdc-text-field__ripple"></span>
            <input aria-controls="description-helper-text-id" aria-describedby="description-helper-text-id"
                   aria-labelledby="description-id" class="mdc-text-field__input"
                   type="text" v-model="form.description">
            <span class="mdc-floating-label" id="description-id">Description</span>
            <span class="mdc-line-ripple"></span>
        </label>
        <div aria-hidden="true" class="mdc-text-field-helper-line" id="description-helper-text-id">
            <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg"
                 v-mdc-text-field-helper-text>
                {{errors.description}}
            </div>
        </div>

        <div class="mdc-select"
             v-mdc-select="{value: form.type, valid: !errors.type, onChange: setType, required: true}">
            <div class="mdc-select__anchor">
                <span class="mdc-select__dropdown-icon"></span>
                <div aria-controls="type-helper-text-id" aria-describedby="type-helper-text-id"
                     aria-haspopup="listbox" aria-labelledby="type-label-id type-selected-text-id"
                     class="mdc-select__selected-text" id="type-selected-text-id"
                     role="button"></div>
                <span class="mdc-floating-label" id="type-label-id">Type</span>
                <div class="mdc-line-ripple"></div>
            </div>
            <div class="mdc-select__menu mdc-menu mdc-menu-surface" role="listbox">
                <ul class="mdc-list">
                    <li aria-selected="false" class="mdc-list-item" data-value="boolean" role="option">Toggle</li>
                    <li aria-selected="false" class="mdc-list-item" data-value="string" role="option">String</li>
                    <li aria-selected="false" class="mdc-list-item" data-value="number" role="option">Number</li>
                </ul>
            </div>
        </div>
        <div aria-hidden="true" class="mdc-select-helper-text mdc-select-helper-text--validation-msg"
             id="type-helper-text-id" v-mdc-select-helper-text>
            {{errors.type}}
        </div>

        <div class="ft-switch" role="presentation" v-if="form.type === types.Boolean">
            <div class="mdc-switch" v-mdc-switch>
                <div class="mdc-switch__track"></div>
                <div class="mdc-switch__thumb-underlay">
                    <div class="mdc-switch__thumb"></div>
                    <input class="mdc-switch__native-control"
                           id="value-boolean-id"
                           role="switch" type="checkbox"
                           v-bind:aria-checked="form.value === true" v-model="form.value">
                </div>
            </div>
            <label for="value-boolean-id">Off/On</label>
        </div>
        <label class="mdc-text-field" v-if="form.type === types.Number"
               v-mdc-text-field="{value: form.value, valid: !errors.value}">
            <span class="mdc-text-field__ripple"></span>
            <input aria-controls="value-number-helper-text-id" aria-describedby="value-number-helper-text-id"
                   aria-labelledby="value-number-id" class="mdc-text-field__input" type="number"
                   v-model.number="form.value">
            <span class="mdc-floating-label" id="value-number-id">Value</span>
            <span class="mdc-line-ripple"></span>
        </label>
        <div aria-hidden="true" class="mdc-text-field-helper-line" id="value-number-helper-text-id"
             v-if="form.type === types.Number">
            <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg"
                 v-mdc-text-field-helper-text>
                {{errors.value}}
            </div>
        </div>
        <label class="mdc-text-field" v-if="form.type === types.String"
               v-mdc-text-field="{value: form.value, valid: !errors.value}">
            <span class="mdc-text-field__ripple"></span>
            <input aria-controls="value-string-helper-text-id" aria-describedby="value-string-helper-text-id"
                   aria-labelledby="value-string-id" class="mdc-text-field__input" type="text"
                   v-model="form.value">
            <span class="mdc-floating-label" id="value-string-id">Value</span>
            <span class="mdc-line-ripple"></span>
        </label>
        <div aria-hidden="true" class="mdc-text-field-helper-line" id="value-string-helper-text-id"
             v-if="form.type === types.String">
            <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg"
                 v-mdc-text-field-helper-text>
                {{errors.value}}
            </div>
        </div>

        <pre class="ft-feature-preview">{{preview}}</pre>

        <div class="ft-form-controls">

            <div class="mdc-touch-target-wrapper">
                <button class="mdc-button" type="button" v-mdc-button v-on:click="cancel()">
                    <span class="mdc-button__ripple"></span>
                    Cancel
                </button>
            </div>

            <div class="mdc-touch-target-wrapper">
                <button class="mdc-button mdc-button--unelevated" type="submit" v-bind:disabled="!isValid" v-mdc-button>
                    <span class="mdc-button__ripple"></span>
                    Save
                </button>
            </div>

        </div>

    </form>
</template>

<script lang="ts">
  import mdcButton from '@/modules/material-components-web/directives/mdc-button';
  import mdcSelect from '@/modules/material-components-web/directives/mdc-select';
  import mdcSelectHelperText from '@/modules/material-components-web/directives/mdc-select-helper-text';
  import mdcSwitch from '@/modules/material-components-web/directives/mdc-switch';
  import mdcTextField from '@/modules/material-components-web/directives/mdc-text-field';
  import mdcTextFieldHelperText from '@/modules/material-components-web/directives/mdc-text-field-helper-text';
  import {
    Feature,
    FeatureValueType,
    featureValueTypes,
    getUpdatedValue,
    normalizeValues,
    toFormValue
  } from '@feature-toggles/helpers';
  import { computed, reactive, SetupContext, watchEffect } from '@vue/composition-api';
  import Vue, { ComponentOptions } from 'vue';

  const componentOptions: ComponentOptions<Vue> = {
    props: {
      data: { type: Object, default: () => ({}) },
    },
    setup(props: { data?: Feature }, context: SetupContext) {

      const form = reactive<Partial<Feature>>({
        key: '',
        description: '',
        type: null,
        value: null
      });

      let data: Feature | undefined;

      watchEffect(() => {
        if (props.data !== data) {
          data = props.data;
          const normalizedValues = normalizeValues(props.data);
          form.key = normalizedValues.key;
          form.description = normalizedValues.description;
          form.type = normalizedValues.type;
          form.value = normalizedValues.value;
        }
      });

      const getErrors = () => {

        const errors: { [key in keyof Feature]?: string } = {};

        if (!form.key) {
          errors.key = 'This is required';
        }

        if (!form.type) {
          errors.type = 'This is required';
        } else if (!featureValueTypes.includes(form.type)) {
          errors.type = 'Value not allowed';
        }

        return errors;

      };

      const errors = computed<{ [key in keyof Feature]?: string }>(getErrors);
      const isValid = computed<boolean>(() => !Object.keys(getErrors()).length);

      const preview = computed<string>(() => JSON.stringify({ [`${form.key}`]: form.value }, null, 2));

      const cancel = () => context.emit('ftCancel');

      const submit = () => context.emit('ftSubmit', {
        ...(props.data || {}),
        key: form.key,
        description: form.description,
        type: form.type,
        value: form.value
      });

      const updateValue = (type: FeatureValueType) => {
        const value = form.value;
        const newValue = getUpdatedValue(value, type);
        if (newValue !== value) {
          form.value = newValue;
        }
      };

      const setType = (value: FeatureValueType) => {
        if (form.type !== value) {
          form.type = value;
          updateValue(value);
        }
      };

      return { form, preview, cancel, submit, errors, isValid, setType, types: FeatureValueType, toFormValue };

    },
    directives: { mdcTextField, mdcTextFieldHelperText, mdcButton, mdcSelect, mdcSelectHelperText, mdcSwitch }
  };

  export default componentOptions;
</script>

<style lang="scss" scoped></style>

// apps/react/src/components/feature-form/FeatureForm.tsx
import {
  Feature,
  FeatureValueType,
  featureValueTypes,
  getUpdatedValue,
  normalizeValues,
  toFormValue
} from '@feature-toggles/helpers';
import { useFormik } from 'formik';
import React, { useEffect } from 'react';
import MDCButton from '../../modules/material-components-web/components/MDCButton';
import MDCSelect from '../../modules/material-components-web/components/MDCSelect';
import MDCSelectHelperText from '../../modules/material-components-web/components/MDCSelectHelperText';
import MDCSwitch from '../../modules/material-components-web/components/MDCSwitch';
import MDCTextField from '../../modules/material-components-web/components/MDCTextField';
import MDCTextFieldHelperText from '../../modules/material-components-web/components/MDCTextFieldHelperText';
import './FeatureForm.scss';

function FeatureForm(props: { data?: Feature, onCancel: () => any, onSubmit: (values: Feature) => any }) {

  const form = useFormik<Feature>({
    initialValues: normalizeValues(props.data),
    validate: values => {

      const errors: { [key in keyof Feature]?: string } = {};

      if (!values.key) {
        errors.key = 'This is required';
      }

      if (!values.type) {
        errors.type = 'This is required';
      } else if (!featureValueTypes.includes(values.type)) {
        errors.type = 'Value not allowed';
      }

      return errors;

    },
    onSubmit: values => props.onSubmit(values)
  });

  const setType = (value: FeatureValueType) => {
    if (form.values.type !== value) {
      form.setFieldValue('type', value);
      updateValue(value);
    }
  };

  const updateValue = (type: FeatureValueType) => {
    const value = form.values.value;
    const newValue = getUpdatedValue(value, type);
    if (newValue !== value) {
      form.setFieldValue('value', newValue);
    }
  };

  useEffect(() => {
    form.setValues(normalizeValues(props.data), true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.data]);

  const preview = (): string => JSON.stringify({ [`${form.values.key}`]: form.values.value }, null, 2);

  return (
    <form onSubmit={form.handleSubmit} className="ft-form" noValidate>

      <MDCTextField className="mdc-text-field" required={true} valid={!form.touched.key || !form.errors.key}
                    value={form.values.key}>
        <span className="mdc-text-field__ripple"/>
        <input aria-controls="key-helper-text-id" aria-describedby="key-helper-text-id" aria-labelledby="key-id"
               className="mdc-text-field__input" type="text" name="key" value={form.values.key}
               onChange={form.handleChange} onBlur={form.handleBlur}
               autoFocus/>
        <span className="mdc-floating-label" id="key-id">Key</span>
        <span className="mdc-line-ripple"/>
      </MDCTextField>
      <div aria-hidden="true" className="mdc-text-field-helper-line" id="key-helper-text-id">
        {form.errors.key ?
          <MDCTextFieldHelperText
            className="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg">{form.errors.key}</MDCTextFieldHelperText>
          : <MDCTextFieldHelperText className="mdc-text-field-helper-text">This will be used as key in the response
            object</MDCTextFieldHelperText>}
      </div>

      <MDCTextField className="mdc-text-field" valid={!form.touched.description || !form.errors.description}
                    value={form.values.description}>
        <span className="mdc-text-field__ripple"/>
        <input aria-controls="description-helper-text-id" aria-describedby="description-helper-text-id"
               aria-labelledby="description-id"
               className="mdc-text-field__input" type="text" name="description" value={form.values.description}
               onChange={form.handleChange} onBlur={form.handleBlur}/>
        <span className="mdc-floating-label" id="description-id">Description</span>
        <span className="mdc-line-ripple"/>
      </MDCTextField>
      <div aria-hidden="true" className="mdc-text-field-helper-line" id="description-helper-text-id">
        <MDCTextFieldHelperText
          className="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg">{form.errors.description}</MDCTextFieldHelperText>
      </div>

      <MDCSelect className="mdc-select" required={true} valid={!form.touched.type || !form.errors.type}
                 value={form.values.type}
                 onChange={(value: FeatureValueType) => setType(value)}>
        <div className="mdc-select__anchor">
          <span className="mdc-select__dropdown-icon"/>
          <div aria-controls="type-helper-text-id" aria-describedby="type-helper-text-id"
               aria-haspopup="listbox" aria-labelledby="type-label-id type-selected-text-id"
               className="mdc-select__selected-text" id="type-selected-text-id"
               role="button"/>
          <span className="mdc-floating-label" id="type-label-id">Type</span>
          <div className="mdc-line-ripple"/>
        </div>
        <div className="mdc-select__menu mdc-menu mdc-menu-surface" role="listbox">
          <ul className="mdc-list">
            <li className="mdc-list-item" data-value="boolean" role="option" aria-selected="false">Toggle</li>
            <li className="mdc-list-item" data-value="string" role="option" aria-selected="false">String</li>
            <li className="mdc-list-item" data-value="number" role="option" aria-selected="false">Number</li>
          </ul>
        </div>
      </MDCSelect>
      <MDCSelectHelperText aria-hidden="true" className="mdc-select-helper-text mdc-select-helper-text--validation-msg"
                           id="type-helper-text-id">{form.errors.type}</MDCSelectHelperText>

      {form.values.type === FeatureValueType.Boolean ?
        <div className="ft-switch" role="presentation">
          <MDCSwitch className="mdc-switch">
            <div className="mdc-switch__track"/>
            <div className="mdc-switch__thumb-underlay">
              <div className="mdc-switch__thumb"/>
              <input aria-checked={form.values.value === true} className="mdc-switch__native-control"
                     id="value-boolean-id"
                     role="switch" type="checkbox" name="value" defaultChecked={form.values.value === true}
                     onChange={form.handleChange} onBlur={form.handleBlur}/>
            </div>
          </MDCSwitch>
          <label htmlFor="value-boolean-id">Off/On</label>
        </div>
        : null}

      {form.values.type === FeatureValueType.Number ?
        <>
          <MDCTextField className="mdc-text-field" valid={!form.touched.value || !form.errors.value}
                        value={form.values.value}>
            <span className="mdc-text-field__ripple"/>
            <input aria-controls="value-helper-text-id" aria-describedby="value-helper-text-id"
                   aria-labelledby="value-id"
                   className="mdc-text-field__input" type="number" name="value"
                   value={toFormValue(form.values.value)}
                   onChange={form.handleChange} onBlur={form.handleBlur}/>
            <span className="mdc-floating-label" id="value-id">Value</span>
            <span className="mdc-line-ripple"/>
          </MDCTextField>
          <div aria-hidden="true" className="mdc-text-field-helper-line" id="value-helper-text-id">
            <MDCTextFieldHelperText
              className="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg">{form.errors.value}</MDCTextFieldHelperText>
          </div>
        </>
        : null}

      {form.values.type === FeatureValueType.String ?
        <>
          <MDCTextField className="mdc-text-field" valid={!form.touched.value || !form.errors.value}
                        value={form.values.value}>
            <span className="mdc-text-field__ripple"/>
            <input aria-controls="value-helper-text-id" aria-describedby="value-helper-text-id"
                   aria-labelledby="value-id"
                   className="mdc-text-field__input" type="text" name="value"
                   value={toFormValue(form.values.value)}
                   onChange={form.handleChange} onBlur={form.handleBlur}/>
            <span className="mdc-floating-label" id="value-id">Value</span>
            <span className="mdc-line-ripple"/>
          </MDCTextField>
          <div aria-hidden="true" className="mdc-text-field-helper-line" id="value-helper-text-id">
            <MDCTextFieldHelperText
              className="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg">{form.errors.value}</MDCTextFieldHelperText>
          </div>
        </>
        : null}

      <pre className="ft-feature-preview">{preview()}</pre>

      <div className="ft-form-controls">

        <div className="mdc-touch-target-wrapper">
          <MDCButton
            onClick={props.onCancel} className="mdc-button" type="button">
            <span className="mdc-button__ripple"/>
            Cancel
          </MDCButton>
        </div>

        <div className="mdc-touch-target-wrapper">
          <MDCButton disabled={!form.isValid} className="mdc-button mdc-button--unelevated" type="submit">
            <span className="mdc-button__ripple"/>
            Save
          </MDCButton>
        </div>

      </div>

    </form>
  );

}

export default FeatureForm;
