// apps/react/src/components/features-list/FeaturesList.tsx
import { Feature } from '@feature-toggles/helpers';
import React from 'react';
import FeatureListItem from '../feature-list-item/FeatureListItem';
import './FeaturesList.scss';

function FeaturesList(props: { data: Feature[] }) {

  return (
    <ul className="FeaturesList ft-cards-list">
      {props.data.map(item => <li key={item._id}><FeatureListItem data={item}/></li>)}
    </ul>
  );

}

export default FeaturesList;

// apps/vue/src/components/FeaturesList.vue
<template>
    <ul class="ft-cards-list">
        <li v-for="item of data" v-bind:key="item._id">
            <FeatureListItem v-bind:data="item"/>
        </li>
    </ul>
</template>

<script lang="ts">
  import FeatureListItem from '@/components/FeatureListItem.vue';

  export default {
    props: {
      data: { type: Array, default: () => [] }
    },
    setup() {
      return {};
    },
    components: {
      FeatureListItem
    }
  };
</script>

<style lang="scss" scoped></style>
