// apps/angular/src/app/components/feature-list-item/feature-list-item.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Feature } from '@feature-toggles/helpers';

@Component({
  selector: 'ft-feature-list-item',
  templateUrl: './feature-list-item.component.html',
  styleUrls: ['./feature-list-item.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FeatureListItemComponent {

  @Input() public data: Feature;

  public get value(): string {
    return JSON.stringify(this.data?.value);
  }

}

<div class="mdc-card mdc-card--outlined" mdcCard>
  <a [routerLink]="['/features', data._id]" class="mdc-card__primary-action ft-card-content">
    <h2 class="mdc-typography--headline6">{{data.key}}</h2>
    <p *ngIf="data.description" class="mdc-typography--subtitle2">{{data.description}}</p>
    <div role="presentation" class="feature-value">
      <pre>{{value}}</pre>
    </div>
  </a>
</div>

<!--<div class="mdc-card mdc-card&#45;&#45;outlined" mdcCard>
  <a [routerLink]="['/features', data._id]" class="mdc-card__primary-action ft-card-content">
    <h2 class="mdc-typography&#45;&#45;headline6">{{key}}: <span>{{value}}</span></h2>
    <p *ngIf="data.description" class="mdc-typography&#45;&#45;subtitle2">{{data.description}}</p>
  </a>
</div>-->

// apps/vue/src/components/FeatureListItem.vue
<template>
  <div v-mdc-card class="mdc-card mdc-card--outlined">
    <a class="mdc-card__primary-action ft-card-content" v-on:click="showDetails()">
      <h2 class="mdc-typography--headline6">{{ data.key }}</h2>
      <p v-if="data.description" class="mdc-typography--subtitle2">{{ data.description }}</p>
      <div class="feature-value" role="presentation">
        <pre>{{ value }}</pre>
      </div>
    </a>
  </div>
</template>

<script lang="ts">
import mdcCard from '@/modules/material-components-web/directives/mdc-card';
import { Feature } from '@feature-toggles/helpers';
import { Component, computed } from 'vue';
import { useRouter } from 'vue-router';

const component: Component = {
  props: {
    data: { type: Object, default: () => ({}) },
  },
  setup(props: { data?: Feature }) {

    const router = useRouter();
    const showDetails = () => router.push(`/feature/${props.data?._id}`);

    const value = computed(() => JSON.stringify(props.data?.value));

    return { value, showDetails };

  },
  directives: { mdcCard }
};

export default component;
</script>

<style lang="scss" scoped></style>
