// apps/react/src/components/feature-list-item/FeatureListItem.tsx
import { Feature } from '@feature-toggles/helpers';
import React from 'react';
import { useHistory } from 'react-router-dom';
import MDCCard from '../../modules/material-components-web/components/MDCCard';
import './FeatureListItem.scss';

function FeatureListItem(props: { data: Feature }) {

  const history = useHistory();
  const navigate = (path: string, event: React.UIEvent) => {
    event.preventDefault();
    history.push(path);
  };

  return (
    <MDCCard className="FeatureListItem mdc-card mdc-card--outlined">
      <a href={`/feature/${props.data._id}`} onClick={event => navigate(`/feature/${props.data._id}`, event)}
         className="mdc-card__primary-action ft-card-content">
        <h2 className="mdc-typography--headline6">{props.data.key}</h2>
        {props.data.description && <p className="mdc-typography--subtitle2">{props.data.description}</p>}
        <div role="presentation" className="feature-value">
          <pre>{JSON.stringify(props.data.value)}</pre>
        </div>
      </a>
    </MDCCard>
  );

}

export default FeatureListItem;

// apps/vue/src/components/FeatureListItem.vue
<template>
  <div v-mdc-card class="mdc-card mdc-card--outlined">
    <a class="mdc-card__primary-action ft-card-content" v-on:click="showDetails()">
      <h2 class="mdc-typography--headline6">{{ data.key }}</h2>
      <p v-if="data.description" class="mdc-typography--subtitle2">{{ data.description }}</p>
      <div class="feature-value" role="presentation">
        <pre>{{ value }}</pre>
      </div>
    </a>
  </div>
</template>

<script lang="ts">
import mdcCard from '@/modules/material-components-web/directives/mdc-card';
import { Feature } from '@feature-toggles/helpers';
import { Component, computed } from 'vue';
import { useRouter } from 'vue-router';

const component: Component = {
  props: {
    data: { type: Object, default: () => ({}) },
  },
  setup(props: { data?: Feature }) {

    const router = useRouter();
    const showDetails = () => router.push(`/feature/${props.data?._id}`);

    const value = computed(() => JSON.stringify(props.data?.value));

    return { value, showDetails };

  },
  directives: { mdcCard }
};

export default component;
</script>

<style lang="scss" scoped></style>
