// apps/vue/src/components/Feature.vue
<template>
  <div role="presentation">

    <header v-mdc-top-app-bar class="mdc-top-app-bar mdc-top-app-bar--fixed">
      <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
          <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button"
                  v-on:click="showList()">
            arrow_back
          </button>
          <h1 class="mdc-top-app-bar__title">{{ addingNew ? 'Add feature' : 'Edit feature' }}</h1>
        </section>
      </div>
    </header>

    <div class="mdc-drawer-app-content mdc-top-app-bar--fixed-adjust">
      <main class="ft-main-content">
        <FeatureForm v-bind:data="data" v-on:ftCancel="showList()" v-on:ftSubmit="addOrUpdate"/>
      </main>
    </div>

  </div>
</template>

<script lang="ts">
import FeatureForm from '@/components/FeatureForm.vue';
import mdcTopAppBar from '@/modules/material-components-web/directives/mdc-top-app-bar';
import { Feature, FeatureService } from '@feature-toggles/helpers';
import { Component, onBeforeUnmount, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const component: Component = {
  setup() {

    const route = useRoute();
    const id = route.params.id;
    const addingNew = ref<boolean>(id === 'new');

    const router = useRouter();
    const showList = () => router.push('/features');

    const data = ref<Feature>();

    let cancelGetRequest: Function;
    onMounted(() => {
      if (!addingNew.value) {
        const { request, cancelRequest } = FeatureService.get(id);
        cancelGetRequest = cancelRequest;
        (async () => data.value = await request)();
      }
    });

    onBeforeUnmount(() => cancelGetRequest && cancelGetRequest());

    let cancelAddOrUpdateRequest: Function;
    const addOrUpdate = (data: Feature) => {
      cancelAddOrUpdateRequest && cancelAddOrUpdateRequest();
      const { request, cancelRequest } = addingNew.value ? FeatureService.add(data) : FeatureService.update(data);
      cancelAddOrUpdateRequest = cancelRequest;
      (async () => {
        await request;
        showList();
      })();
    };

    return { addingNew, showList, data, addOrUpdate };

  },
  components: { FeatureForm },
  directives: { mdcTopAppBar }
};

export default component;
</script>

<style lang="scss" scoped></style>

// apps/react/src/components/feature/Feature.tsx
import { Canceler } from 'axios';
import React, { useEffect, useRef, useState } from 'react';
import { useHistory, useParams } from 'react-router-dom';
import { Feature as FeatureInterface, FeatureService } from '@feature-toggles/helpers';
import MDCTopAppBar from '../../modules/material-components-web/components/MDCTopAppBar';
import FeatureForm from '../feature-form/FeatureForm';
import './Feature.scss';

function Feature() {

  const { id } = useParams();
  const addingNew = id === 'new';

  const [data, setData] = useState<FeatureInterface>();
  const history = useHistory();

  const cancelGetRequest = useRef<Canceler>();

  const cancelAddOrUpdateRequest = useRef<Canceler>();
  const addOrUpdate = (data: FeatureInterface) => {
    cancelAddOrUpdateRequest.current && cancelAddOrUpdateRequest.current();
    const { cancelRequest, request } = addingNew ? FeatureService.add(data) : FeatureService.update(data);
    cancelAddOrUpdateRequest.current = cancelRequest;
    (async () => {
      await request;
      history.push('/features');
    })();
  };

  useEffect(() => {
    cancelGetRequest.current && cancelGetRequest.current();
    if (addingNew) {
      setData(undefined);
    } else {
      const { cancelRequest, request } = FeatureService.get(id);
      cancelGetRequest.current = cancelRequest;
      (async () => setData(await request))();
    }
    return cancelGetRequest.current;
  }, [id, addingNew]);

  return (
    <div className="Feature">

      <MDCTopAppBar className="mdc-top-app-bar mdc-top-app-bar--fixed">
        <div className="mdc-top-app-bar__row">
          <section className="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button onClick={() => history.push('/features')}
                    className="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button">
              arrow_back
            </button>
            <h1 className="mdc-top-app-bar__title">{addingNew ? 'Add feature' : 'Edit feature'}</h1>
          </section>
        </div>
      </MDCTopAppBar>

      <div className="mdc-drawer-app-content mdc-top-app-bar--fixed-adjust">
        <main className="ft-main-content">
          <FeatureForm data={data} onCancel={() => history.push('/features')} onSubmit={values => addOrUpdate(values)}/>
        </main>
      </div>

    </div>
  );

}

export default Feature;
