// apps/react/src/components/features-list/FeaturesList.tsx
import { Feature } from '@feature-toggles/helpers';
import React from 'react';
import FeatureListItem from '../feature-list-item/FeatureListItem';
import './FeaturesList.scss';

function FeaturesList(props: { data: Feature[] }) {

  return (
    <ul className="FeaturesList ft-cards-list">
      {props.data.map(item => <li key={item._id}><FeatureListItem data={item}/></li>)}
    </ul>
  );

}

export default FeaturesList;

// apps/angular/src/app/components/features-list/features-list.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Feature } from '@feature-toggles/helpers';

@Component({
  selector: 'ft-features-list',
  templateUrl: './features-list.component.html',
  styleUrls: ['./features-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FeaturesListComponent {

  @Input() public data: Feature[];

  public trackById(index: number, item: Feature) {
    return item._id;
  }

}

<ul class="ft-cards-list">
  <li *ngFor="let item of data; trackBy: trackById">
    <ft-feature-list-item [data]="item"></ft-feature-list-item>
  </li>
</ul>
