// apps/vue/src/components/Feature.vue
<template>
    <div role="presentation">

        <header class="mdc-top-app-bar mdc-top-app-bar--fixed" v-mdc-top-app-bar>
            <div class="mdc-top-app-bar__row">
                <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
                    <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button"
                            v-on:click="showList()">
                        arrow_back
                    </button>
                    <h1 class="mdc-top-app-bar__title">{{addingNew ? 'Add feature' : 'Edit feature'}}</h1>
                </section>
            </div>
        </header>

        <div class="mdc-drawer-app-content mdc-top-app-bar--fixed-adjust">
            <main class="ft-main-content">
                <FeatureForm v-bind:data="data" v-on:ftCancel="showList()" v-on:ftSubmit="addOrUpdate"/>
            </main>
        </div>

    </div>
</template>

<script lang="ts">
  import FeatureForm from '@/components/FeatureForm.vue';
  import mdcTopAppBar from '@/modules/material-components-web/directives/mdc-top-app-bar';
  import { FeatureService } from '@/services/feature.service';
  import { onBeforeUnmount, onMounted, ref, SetupContext } from '@vue/composition-api';
  import Vue, { ComponentOptions } from 'vue';
  import { Feature } from '~express/models/feature';

  const componentOptions: ComponentOptions<Vue> = {
    setup(props: {}, context: SetupContext) {

      const id = context.root.$route.params.id;
      const addingNew = ref<boolean>(id === 'new');

      const router = context.root.$router;
      const showList = () => router.push('/features');

      const data = ref<Feature>();

      let cancelGetRequest: Function;
      onMounted(() => {
        if (!addingNew.value) {
          const { request, cancelRequest } = FeatureService.get(id);
          cancelGetRequest = cancelRequest;
          (async () => data.value = await request)();
        }
      });

      onBeforeUnmount(() => cancelGetRequest && cancelGetRequest());

      let cancelAddOrUpdateRequest: Function;
      const addOrUpdate = (data: Feature) => {
        cancelAddOrUpdateRequest && cancelAddOrUpdateRequest();
        const { request, cancelRequest } = addingNew.value ? FeatureService.add(data) : FeatureService.update(data);
        cancelAddOrUpdateRequest = cancelRequest;
        (async () => {
          await request;
          showList();
        })();
      };

      return { addingNew, showList, data, addOrUpdate };

    },
    components: { FeatureForm },
    directives: { mdcTopAppBar }
  };

  export default componentOptions;
</script>

<style lang="scss" scoped></style>

// apps/angular/src/app/components/feature/feature.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { of, Subscription } from 'rxjs';
import { distinctUntilChanged, map, switchMap, tap } from 'rxjs/operators';
import { Feature } from '~express/models/feature';
import { FeatureService } from '../../services/feature.service';

@Component({
  selector: 'ft-feature',
  templateUrl: './feature.component.html',
  styleUrls: ['./feature.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FeatureComponent implements OnInit, OnDestroy {

  public addingNew: boolean;
  public data: Feature;
  private dataSubscription: Subscription;
  private saveSubscription: Subscription;

  constructor(private activatedRoute: ActivatedRoute,
              private router: Router,
              private featureService: FeatureService,
              private cdr: ChangeDetectorRef) {
  }

  public ngOnInit(): void {
    this.dataSubscription = this.activatedRoute.params.pipe(
      map(params => params.id),
      distinctUntilChanged(),
      tap(id => this.addingNew = id === 'new'),
      switchMap(id => this.addingNew ? of(null) : this.featureService.get(id))
    ).subscribe(data => {
      this.data = data;
      this.cdr.markForCheck();
    });
  }

  public addOrUpdate(data: Feature): void {

    if (this.saveSubscription) {
      this.saveSubscription.unsubscribe();
    }

    const saveObservable = this.addingNew ? this.featureService.add(data) : this.featureService.update(data);
    this.saveSubscription = saveObservable.subscribe(() => this.showList());

  }

  public showList() {
    this.router.navigate(['/features']);
  }

  public ngOnDestroy(): void {

    if (this.dataSubscription) {
      this.dataSubscription.unsubscribe();
    }

    if (this.saveSubscription) {
      this.saveSubscription.unsubscribe();
    }

  }

}

<header class="mdc-top-app-bar mdc-top-app-bar--fixed" mdcTopAppBar>
  <div class="mdc-top-app-bar__row">
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <button (click)="showList()" class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button">
        arrow_back
      </button>
      <h1 class="mdc-top-app-bar__title">{{addingNew ? 'Add feature' : 'Edit feature'}}</h1>
    </section>
  </div>
</header>

<div class="mdc-drawer-app-content mdc-top-app-bar--fixed-adjust">
  <main class="ft-main-content">
    <ft-feature-form (ftCancel)="showList()" (ftSubmit)="addOrUpdate($event)" *ngIf="data || addingNew"
                     [data]="data"></ft-feature-form>
  </main>
</div>
