// apps/vue/src/components/Features.vue
<template>
  <div role="presentation">

    <header v-mdc-top-app-bar class="mdc-top-app-bar mdc-top-app-bar--fixed">
      <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
          <h1 class="mdc-top-app-bar__title">Feature toggles</h1>
        </section>
      </div>
    </header>

    <div class="mdc-top-app-bar--fixed-adjust" role="presentation">

      <main class="ft-main-content">
        <FeaturesList v-bind:data="data"/>
      </main>

      <button v-mdc-fab aria-label="Add feature" class="mdc-fab ft-fab-absolute" type="button"
              v-on:click="addNew()">
        <span class="mdc-fab__ripple"></span>
        <span class="mdc-fab__icon material-icons">add</span>
      </button>

    </div>

  </div>
</template>

<script lang="ts">
import FeaturesList from '@/components/FeaturesList.vue';
import mdcFab from '@/modules/material-components-web/directives/mdc-fab';
import mdcTopAppBar from '@/modules/material-components-web/directives/mdc-top-app-bar';
import { Feature, FeaturesService } from '@feature-toggles/helpers';
import { Component, onBeforeUnmount, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

const component: Component = {
  setup() {

    const router = useRouter();
    const addNew = () => router.push('/feature/new');

    const data = ref<Feature[]>();

    let cancelRequest: Function;

    onMounted(() => {
      let request: Promise<Feature[]>;
      ({ request, cancelRequest } = FeaturesService.getAll());
      (async () => data.value = await request)();
    });

    onBeforeUnmount(() => cancelRequest && cancelRequest());

    return { addNew, data };

  },
  components: { FeaturesList },
  directives: { mdcFab, mdcTopAppBar }
};

export default component;
</script>

<style lang="scss" scoped></style>

// apps/react/src/components/features/Features.tsx
import { Feature, FeaturesService } from '@feature-toggles/helpers';
import React, { useEffect, useState } from 'react';
import { useHistory } from 'react-router-dom';
import MDCFab from '../../modules/material-components-web/components/MDCFab';
import MDCTopAppBar from '../../modules/material-components-web/components/MDCTopAppBar';
import FeaturesList from '../features-list/FeaturesList';
import './Features.scss';

function Features() {

  const [data, setData] = useState<Feature[]>([]);
  const history = useHistory();

  useEffect(() => {
    const { request, cancelRequest } = FeaturesService.getAll();
    (async () => setData(await request))();
    return cancelRequest;
  }, []);

  return (
    <div className="Features">

      <MDCTopAppBar className="mdc-top-app-bar mdc-top-app-bar--fixed">
        <div className="mdc-top-app-bar__row">
          <section className="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <h1 className="mdc-top-app-bar__title">Feature toggles</h1>
          </section>
        </div>
      </MDCTopAppBar>

      <div className="mdc-top-app-bar--fixed-adjust" role="presentation">

        <main className="ft-main-content">
          <FeaturesList data={data}/>
        </main>

        <MDCFab onClick={() => history.push('/feature/new')} aria-label="Add feature"
                className="mdc-fab ft-fab-absolute" type="button">
          <span className="mdc-fab__ripple"/>
          <span className="mdc-fab__icon material-icons">add</span>
        </MDCFab>

      </div>

    </div>
  );

}

export default Features;
