// apps/react/src/components/features/Features.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Feature } from '../../../../express/src/models/feature';
import { FeaturesService } from '../../services/features.service';
import MDCFab from '../material-components-web/MDCFab';
import MDCTopAppBar from '../material-components-web/MDCTopAppBar';
import './Features.scss';

function Features() {

  const [data, setData] = useState<Feature[]>([]);

  useEffect(() => {
    (async () => setData(await FeaturesService.getAll()))();
  }, []);

  return (
    <div className="Features">

      <MDCTopAppBar className="mdc-top-app-bar mdc-top-app-bar--fixed">
        <div className="mdc-top-app-bar__row">
          <section className="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <h1 className="mdc-top-app-bar__title">Feature toggles</h1>
          </section>
        </div>
      </MDCTopAppBar>

      <div className="mdc-top-app-bar--fixed-adjust" role="presentation">

        <main className="ft-main-content">
          {/*TODO: <Features-list/>*/}
          {JSON.stringify(data)}
        </main>

        <Link to="/feature/new">
          <MDCFab aria-label="Add feature" className="mdc-fab ft-fab-absolute" type="button">
            <span className="mdc-fab__ripple"/>
            <span className="mdc-fab__icon material-icons">add</span>
          </MDCFab>
        </Link>

      </div>

    </div>
  );
}

export default Features;

// apps/angular/src/app/components/features/features.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { Feature } from '~express/models/feature';
import { FeaturesService } from '../../services/features.service';

@Component({
  selector: 'ft-features',
  templateUrl: './features.component.html',
  styleUrls: ['./features.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FeaturesComponent implements OnInit, OnDestroy {

  public data: Feature[];
  private dataSubscription: Subscription;

  constructor(private featuresService: FeaturesService,
              private cdr: ChangeDetectorRef) {
  }

  public ngOnInit(): void {
    this.dataSubscription = this.featuresService.getAll().subscribe(data => {
      this.data = data;
      this.cdr.markForCheck();
    });
  }

  public ngOnDestroy(): void {
    if (this.dataSubscription) {
      this.dataSubscription.unsubscribe();
    }
  }

}

<header class="mdc-top-app-bar mdc-top-app-bar--fixed" mdcTopAppBar>
  <div class="mdc-top-app-bar__row">
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <h1 class="mdc-top-app-bar__title">Feature toggles</h1>
    </section>
  </div>
</header>

<div class="mdc-top-app-bar--fixed-adjust" role="presentation">

  <main class="ft-main-content">
    <ft-features-list [data]="data"></ft-features-list>
  </main>

  <button [routerLink]="['/features', 'new']" aria-label="Add feature" class="mdc-fab ft-fab-absolute" mdcFab
          type="button">
    <div class="mdc-fab__ripple"></div>
    <span class="mdc-fab__icon material-icons">add</span>
  </button>

</div>
